@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

olcnePipeline(
  branchPattern: new BranchPattern(master: 'oracle/release/{{{.major}}}.{{{.minor}}}.{{{.patch}}}', feature: 'feature/.*'),
  customStages: [container: [enabled: false]],
  platforms: ['ol7', 'ol8', 'ol9'],
  architectures: ['x86_64', 'aarch64'],
  yumOL7Repos: ['ol7_addons', 'ol7_developer_golang117'],
  yumOL8Repos:['ol8_appstream'],
  ol8ModulesToDisable: ['go-toolset:ol8', 'go-toolset:ol8addon'],
  yumOL9Repos:['ol9_appstream'],
  golang: '1.22.8'
)
